import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { dark } from "@clerk/themes";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" className="dark">
        <body className={`${poppins.variable} font-sans antialiased`}>
          <header className="border-b">
            <div className="container mx-auto flex justify-between items-center h-16 px-4">
              <div className="flex items-center gap-8">
                <Link href="/" className="font-bold text-xl">Flash Card</Link>
                <nav className="hidden md:flex items-center gap-6">
                  <Link href="/pricing" className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
                    Pricing
                  </Link>
                  <SignedIn>
                    <Link href="/dashboard" className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
                      Dashboard
                    </Link>
                  </SignedIn>
                </nav>
              </div>
              <div className="flex gap-4">
                <SignedOut>
                  <div className="flex gap-2">
                    <SignInButton mode="modal">
                      <Button variant="default">Sign In</Button>
                    </SignInButton>
                    <SignUpButton mode="modal">
                      <Button variant="secondary">Sign Up</Button>
                    </SignUpButton>
                  </div>
                </SignedOut>
                <SignedIn>
                  <div className="flex items-center gap-4">
                    <PlanStatus />
                    <UserButton afterSignOutUrl="/" />
                  </div>
                </SignedIn>
              </div>
            </div>
          </header>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}

async function PlanStatus() {
  const { has } = await auth();
  const isPro = has({ plan: "pro" });

  return (
    <div className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider border ${isPro
      ? "bg-primary/10 border-primary/20 text-primary"
      : "bg-muted border-border text-muted-foreground"
      }`}>
      {isPro ? "Pro" : "Free"}
    </div>
  );
}

